name: CICD

on:
  schedule:
    # Runs at 12:00AM UTC every Monday
    - cron: "0 12 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    name: Update Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update versions
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./update-versions.sh -o data/versions.json

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          commit_message: "chore(data): update versions"
